[FEAT] 홈 API 구현
Team-Lequu/Lequu-Server pull request #34
Opened 2024-01-06 12:57 UTC by dong2ast

## 📌 관련 이슈

closed #8 
## ✨ 어떤 이유로 변경된 내용인지

* 홈 조회 api를 구현했습니다.
* 인기있는 레큐북 6개가 조회됩니다.
* 테스트를 위한 InitDb Component를 구현했습니다.

## 🙏 검토 혹은 리뷰어에게 남기고 싶은 말

* 인기있는 레큐북은 기획단에서 SQL로 수정을 할 수 있기를 원하기에 boolean 필드로 추가했습니다.
* JPA에 limit 쿼리가 지원 안되기에 native 쿼리로 작성했습니다.
* InitDb 데이터는 DB가 실행될 때 초기 데이터로 입력됩니다.

2024-01-06 15:45 UTC, ddongseop requested changes
사소한 오타를 제외하고는 완벽한것 같아요-!

2024-01-06 15:45 UTC, ddongseop commented on src/main/java/org/sopt/lequuServer/domain/note/model/Note.java
> +Note extends BaseTimeEntity {
[P2] 여기 불필요한 엔터가 들어간 것 같아요! 수정 부탁드림당~

2024-01-06 15:45 UTC, ddongseop commented on src/main/java/org/sopt/lequuServer/domain/book/repository/BookRepository.java
> +    List<Book> getAllByPopular(@Param("isPopular") Boolean isPopular, PageRequest pageRequest);
와우 Paging 쓰는거 처음보는데, 신기하군뇨~~

2024-01-06 15:45 UTC, ddongseop commented on src/main/java/org/sopt/lequuServer/domain/book/repository/BookRepository.java
> +    List<Book> getAllByPopular(@Param("isPopular") Boolean isPopular, PageRequest pageRequest);
[P3] 혹시 여기 Book 뒤에 띄어쓰기 한번 더 들어간거 같은데 수정해주실 수 있나요~?

2024-01-06 15:45 UTC, ddongseop commented on src/main/java/org/sopt/lequuServer/domain/book/model/Book.java
> +        return new Book(uuid, favoriteName, favoriteImage, title, description, backgroundColor, member, isPopular);
필드 추가 확인했습니당~

2024-01-06 15:45 UTC, ddongseop commented on src/main/java/org/sopt/lequuServer/InitDb.java
> +public class InitDb {
InitDb 만드는거 귀찮은 작업인데,,, 맛있게 쓰겠습니다,,,

2024-01-07 04:17 UTC, eeddiinn approved these changes
수고하셨습니당 ~~~~!!!👏👏

2024-01-07 04:17 UTC, eeddiinn commented on src/main/java/org/sopt/lequuServer/domain/book/service/BookService.java
> +        return bookRepository.getAllByPopular(true, PageRequest.of(0, 6));
오호 PageRequest에 대해 새롭게 알고갑니다 !!!! 😁

2024-01-07 10:26 UTC, ddongseop approved these changes
헉 어프롭을 안했었네요 고고~~

2024-01-07 10:48 UTC, merged