[FEAT] 홈 화면 즐겨찾기 API 구현
Team-Lequu/Lequu-Server pull request #75
Opened 2024-03-10 16:15 UTC by eeddiinn

## 📌 관련 이슈

closed #74 

## ✨ 어떤 이유로 변경된 내용인지

- 즐겨찾기 기능을 위한 API를 구현했습니다.
- 즐겨찾는 레큐북 등록하기 API는 레큐북 Id와 엑세스 토큰을 받아 즐겨찾기를 등록할 수 있도록 하였습니다.
- 즐겨찾는 레큐북 조회하기 API는 엑세스 토큰을 받아 그 멤버가 즐겨찾기 해놓은 레큐북 목록들을 가져올 수 있도록 하였습니다. 
- 구현을 위해 새로운 엔티티 Favorite을 만들었습니다. 

## 🙏 검토 혹은 리뷰어에게 남기고 싶은 말

- 동섭빠 도와줘서 감사용가링 ! ! 🤩
- 글고 즐겨찾기는 갯수 제한 없나여 ?-?

2024-03-11 13:20 UTC, dong2ast requested changes
고생 많으셨습니다~~ 다른 api처럼 컨트롤러에 interface 단도 추가해주세요~! 👍 👍

2024-03-11 13:20 UTC, dong2ast commented on src/main/java/org/sopt/lequuServer/domain/favorite/facade/FavoriteFacade.java
> +        member.addFavorite(favorite);
[P2] 이런 연관관계 매핑 로직은 일대다 : 다대일 관계를 풀어주는 중간다리 객체를 생성할 때 함께 넣어주는게 추후 실수할 가능성도 줄이고 코드를 깔끔히 하는데도 더 좋습니다!
방법은 아래 예시를 들어드릴게요~

2024-03-11 13:20 UTC, dong2ast commented on src/main/java/org/sopt/lequuServer/domain/favorite/model/Favorite.java
> +    }
```suggestion
    public static Favorite of(Member member, Book book) {
        Favorite favorite = new Favorite(member, book);
        book.addFavorite(favorite);
        member.addFavorite(favorite);
        return favorite;
    }
```
위에서 얘기한 수정 사항입니다~ 이거를 아마 '연관관계 편의성 설정' 뭐 이렇게 불렀던 것 같은데 혹시 더 궁금하면 한번 찾아보세요 :)

2024-03-11 13:20 UTC, dong2ast commented on src/main/java/org/sopt/lequuServer/domain/favorite/model/Favorite.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY)
```
[P1] ManyToOne 관계에서는 기본적으로 지연로딩을 설정하는 것이 좋습니다. 안그러면 N+1 문제가 발생할 수 있어요!
이부분은 구글에 검색해보면 자세히 나올건데 간단히 설명드리면
1. ManyToOne 관계는 기본적으로 EAGER 즉, 즉시로딩이 기본 설정입니다.
2. 따라서 OneToMany 관계에 있는 데이터를 조회할 때 (예를 들면 Member), Member와 연결되어 있는 Favorite 객체도 같이 조회하려고 합니다.
3. 근데 Member 1개에는 여러개의 Favorite이 존재하죠?? 그러면 그 Favorite만큼 DB에 쿼리를 날려서 Favorite 데이터를 가져오게 됩니다.
4. 단지 Member를 1을 조회하려고 한 것 뿐인데 N번의 쿼리가 날라갔죠?? 이게 N+1 문제입니다.

그래서 지연로딩을 걸면 Member를 조회할 때 Favorite의 프록시 객체(이것도 궁금하면 찾아보세영 ㅋㅋ)가 주입되게 되고, 실제 Favorite을 조회하지 않는 이상 추가적인 쿼리가 발생하지 않게 됩니다!

이것도 따봉만 날리고 가봐라 현예진

2024-03-11 13:20 UTC, dong2ast commented on src/main/java/org/sopt/lequuServer/domain/favorite/controller/FavoriteController.java
> +@RequestMapping("api/favorite")
앞에 / 없는거 뭔가... 뭔가.. 불편한데.................

2024-03-12 08:43 UTC, eeddiinn commented on src/main/java/org/sopt/lequuServer/domain/favorite/model/Favorite.java
> +    }
오호 새롭게 알고갑니당 !!!!!

2024-03-12 08:43 UTC, eeddiinn commented on src/main/java/org/sopt/lequuServer/domain/favorite/controller/FavoriteController.java
> +@RequestMapping("api/favorite")
아차차 실수 ......................🤣

2024-03-12 09:58 UTC, ddongseop approved these changes
수고하셨습니다! 동휘가 리뷰 남겨준 부분 다 반영만 한다면 충분할 것 같아요!
추가로, 즐겨찾기 개수 제한 관련해서 논의 후에 알려드리겠습니다!

2024-03-12 13:41 UTC, eeddiinn commented on src/main/java/org/sopt/lequuServer/domain/favorite/model/Favorite.java
> +    @ManyToOne
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ 왕 자세한 설명 감쟈합니다 ...!!!!!! 바로 반영할게유

2024-03-13 04:10 UTC, dong2ast approved these changes

2024-03-13 07:04 UTC, merged