[FEAT] 마이페이지 즐겨찾기 조회 API 구현
Team-Lequu/Lequu-Server pull request #79
Opened 2024-03-17 07:40 UTC by eeddiinn

## 📌 관련 이슈

closed #78 

## ✨ 어떤 이유로 변경된 내용인지

![image](https://github.com/Team-Lecue/Lecue-Server/assets/137388764/d798dafc-596b-42b1-b630-71a99ddf36f4)
옛날 버전 마이페이지

![image](https://github.com/Team-Lecue/Lecue-Server/assets/137388764/8ee593f9-09c2-4c82-93db-7d354f0b2c43)
바뀐 버전 마이페이지 
- 바뀐 마이페이지에서는 닉네임이 필요 없어서 membernickname 을 ResponseDto에서 제거함

- membernickname을 지움에 따라 DTO 리스트가 단일 필드로 들어가 있기 때문에 감싸지 않고 그대로 반환할 수 있도록 Dto 를 하나로 통일시킴  (MypageBooksResponseDto, MypageBookResponseDto    ->    MypageBookResponseDto)

- 마이페이지의 레큐북을 조회할 때 즐겨찾기 여부도 알 수 있도록 ResponseDto에 isFavorite 을 추가함

- 마이페이지의 즐겨찾기를 조회할 때 갯수 제한 없이 즐겨찾기 한 레큐북을 다 조회할 수 있도록 구현함

## 🙏 검토 혹은 리뷰어에게 남기고 싶은 말

- test도 완벽하게 햇슴당 !!
- 혹시 놓친부분이 있으면 알려주세용 😏

2024-03-17 17:54 UTC, ddongseop approved these changes
이제 간단한 작업은 그냥 뚝딱 해내시는 군요!

1. 인덴트 오류는 내일 전체회의 끝나고 디코 화면공유로 좀 봐드리겠습니당
2. https://www.notion.so/rileybyeon/SP-5-9616d2554f8e44d9a8cbadd35ccea22b?pvs=4#1019c7f71dbb4889a3887c0ed9df2eb3 참고해보시면, 마이페이지 홈 화면에서 닉네임을 호출하는 부분이 생겼는데요, 이 부분도 따로 API 따줘야할 것 같습니다!

2024-03-18 00:04 UTC, dong2ast requested changes
전반적으로 잘 해주셨네여 👍 👍 
섭섭님이 얘기한 부분과 제가 얘기한 부분 검토 후 다시 반영해주세요~!

2024-03-18 00:04 UTC, dong2ast commented on src/main/java/org/sopt/lequuServer/domain/member/dto/response/MypageBookResponseDto.java
> +                            .anyMatch(favorite -> favorite.getBook().getId().equals(book.getId()));
[P2] 이 부분 Database Connection이 꽤 많이 발생할 것 같은데 혹시 확인해보셨나요??
몇 번 발생되는지 확인하고 공유해주세요!
많이 발생하는 것 같다면 [간단한 힌트](https://pooney.tistory.com/83) 여기를 참고해서 수정해보세요 :)
(참고로 DB 커넥션 파악하는 법을 잘 모르겠으면 언제든 물어봐도 좋습니다~)

2024-03-18 00:04 UTC, dong2ast commented on src/main/java/org/sopt/lequuServer/domain/member/dto/response/MypageBookResponseDto.java
[P3] DTO 단에서 트랜잭션(혹은 Database 서버와의 통신)이 발생하는 것이 좋을지 한번 고민해보는 것도 좋을 것 같습니다~
(3tier architecture와 계층 분리 측면에서 생각해보면 좋을 것 같아요~ 고민 결과 공유해주시면 감사하겠습니다 😊)

2024-03-18 23:55 UTC, dong2ast approved these changes

2024-03-19 05:57 UTC, merged